home:
  path: /
  controller: App\Controller\HomeController::home
about:
  path: /about
  controller: App\Controller\HomeController::about

watched_link.index:
  path: /watched_link
  controller: App\Controller\WatchedLinkController::index
  methods: GET

watched_link.create:
  path: /watched_link/create
  controller: App\Controller\WatchedLinkController::create
  methods: GET

watched_link.store:
  path: /watched_link
  controller: App\Controller\WatchedLinkController::store
  methods: POST

watched_link.show:
  path: /watched_link/{uri}
  controller: App\Controller\WatchedLinkController::show
  methods: GET

watched_link.edit:
  path: /watched_link/{uri}/edit
  controller: App\Controller\WatchedLinkController::edit
  methods: GET|HEAD

watched_link.update:
  path: /watched_link/{uri}
  controller: App\Controller\WatchedLinkController::update
  methods: PUT|PATCH

watched_link.destroy:
  path: /watched_link/{uri}
  controller: App\Controller\WatchedLinkController::destroy
  methods: DELETE

visit.get_aggregated_visits:
  path: /visits/{watchedLinkId}/{start}/{end}/{scale}
  controller: App\Controller\VisitController::getAggregatedVisits
  methods: GET

index:
  path: /{link_id}
  controller: App\Controller\CountRedirectController::countRedirect
  requirements:
    link_id: '.{1,}'